apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: vllm-my-model
  namespace: hacohen-inference-server
spec:
  deploymentMode: RawDeployment 
  predictor:
    minReplicas: 1
    maxReplicas: 2
    model:
      imagePullSecrets:
        - name: redhat-registry
      modelFormat:
        name: vLLM
      runtime: vllm
      storage:
        key: hf-token-secret
        uri: huggingface://RedHatAI/Llama-3.2-1B-Instruct-FP8
      resources:
        requests:
          cpu: "4"
          memory: "2Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "8"
          memory: "4Gi"
          nvidia.com/gpu: "1"
      env:
        - name: VLLM_LOGGING_LEVEL
          value: DEBUG
