apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: hacohen-inference-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
